// MINNA NO NIHONGO DATA extracted from new.html
var MNN = [
  {n:1, title:'あたらしい ともだち', en:'New Friends',
   grammar:['X は Y です (X is Y)','Question sentences (ですか)','Noun₁ の Noun₂ (possession)'],
   vocab:[{j:'わたし',r:'watashi',e:'I / me'},{j:'あなた',r:'anata',e:'you'},{j:'かた',r:'kata',e:'this person (polite)'},{j:'せんせい',r:'sensei',e:'teacher'},{j:'がくせい',r:'gakusei',e:'student'},{j:'かいしゃいん',r:'kaishain',e:'company employee'},{j:'にほんご',r:'nihongo',e:'Japanese language'},{j:'なまえ',r:'namae',e:'name'},{j:'なん/なに',r:'nan/nani',e:'what'},{j:'〜さん',r:'-san',e:'honorific title'}]},
  {n:2, title:'かいもの', en:'Shopping',
   grammar:['これ/それ/あれ (this/that/that over there)','この/その/あの + Noun','ここ/そこ/あそこ (here/there/over there)','だれの (whose)','Noun も (also/too)','Noun じゃないです (is not)'],
   vocab:[{j:'これ',r:'kore',e:'this'},{j:'それ',r:'sore',e:'that'},{j:'あれ',r:'are',e:'that (far)'},{j:'いくら',r:'ikura',e:'how much'},{j:'ひゃく',r:'hyaku',e:'hundred'},{j:'せん',r:'sen',e:'thousand'},{j:'まん',r:'man',e:'ten thousand'},{j:'たかい',r:'takai',e:'expensive'},{j:'やすい',r:'yasui',e:'cheap'},{j:'かわいい',r:'kawaii',e:'cute'}]},
  {n:3, title:'デートの やくそく', en:'Making a Date',
   grammar:['Verb Conjugation (ます form)','Verb Types — U-verbs and RU-verbs','Particles に (time/destination) を (object)','Time References','〜ませんか (invitation)','Frequency Adverbs','Word Order','Topic Particle は'],
   vocab:[{j:'いきます',r:'ikimasu',e:'go'},{j:'きます',r:'kimasu',e:'come'},{j:'かえります',r:'kaerimasu',e:'return'},{j:'たべます',r:'tabemasu',e:'eat'},{j:'のみます',r:'nomimasu',e:'drink'},{j:'みます',r:'mimasu',e:'watch/see'},{j:'ききます',r:'kikimasu',e:'listen'},{j:'よみます',r:'yomimasu',e:'read'},{j:'はなします',r:'hanashimasu',e:'speak'},{j:'かいます',r:'kaimasu',e:'buy'},{j:'まちます',r:'machimasu',e:'wait'},{j:'まいにち',r:'mainichi',e:'every day'},{j:'ときどき',r:'tokidoki',e:'sometimes'},{j:'たいてい',r:'taitei',e:'usually'},{j:'いつも',r:'itsumo',e:'always'}]},
  {n:4, title:'はじめての デート', en:'The First Date',
   grammar:['X が あります/います (there is X)','Describing where things are','Past tense of です','Past tense of verbs','Particle も','〜時間 (duration)','Particle と (with/and)'],
   vocab:[{j:'あります',r:'arimasu',e:'exist (things)'},{j:'います',r:'imasu',e:'exist (living)'},{j:'うえ',r:'ue',e:'above'},{j:'した',r:'shita',e:'below'},{j:'まえ',r:'mae',e:'front'},{j:'うしろ',r:'ushiro',e:'behind'},{j:'なか',r:'naka',e:'inside'},{j:'そと',r:'soto',e:'outside'},{j:'となり',r:'tonari',e:'next to'},{j:'ちかく',r:'chikaku',e:'near'}]},
  {n:5, title:'おきなわ りょこう', en:'Trip to Okinawa',
   grammar:['Adjectives (present tense)','Adjectives (past tense)','Adjective + Noun modification','すき(な)/きらい(な)','〜ましょう/〜ましょうか','Counting things'],
   vocab:[{j:'おおきい',r:'ookii',e:'big'},{j:'ちいさい',r:'chiisai',e:'small'},{j:'あたらしい',r:'atarashii',e:'new'},{j:'ふるい',r:'furui',e:'old'},{j:'いい',r:'ii',e:'good'},{j:'わるい',r:'warui',e:'bad'},{j:'たのしい',r:'tanoshii',e:'fun'},{j:'おもしろい',r:'omoshiroi',e:'interesting'},{j:'きれい(な)',r:'kirei(na)',e:'beautiful/clean'},{j:'しずか(な)',r:'shizuka(na)',e:'quiet'}]},
  {n:6, title:'ロバートさんの いちにち', en:"A Day in Robert's Life",
   grammar:['て form','〜てください (please do)','〜てもいいです (may I)','〜てはいけません (must not)','〜から (because)','〜ましょうか (shall I)'],
   vocab:[{j:'おきます',r:'okimasu',e:'wake up'},{j:'ねます',r:'nemasu',e:'sleep'},{j:'はたらきます',r:'hatarakimasu',e:'work'},{j:'やすみます',r:'yasumimasu',e:'rest/take off'},{j:'でかけます',r:'dekakemasu',e:'go out'},{j:'すわります',r:'suwarimasu',e:'sit'},{j:'たちます',r:'tachimasu',e:'stand'},{j:'はいります',r:'hairimasu',e:'enter'},{j:'でます',r:'demasu',e:'leave/exit'},{j:'つかいます',r:'tsukaimasu',e:'use'}]},
  {n:7, title:'かぞくの しゃしん', en:'Family Picture',
   grammar:['〜ている (action in progress)','〜ている (result of change)','Adjective/Noun て forms for joining','Verb Stem + に行く','Counting people'],
   vocab:[{j:'かぞく',r:'kazoku',e:'family'},{j:'ちち',r:'chichi',e:'my father'},{j:'はは',r:'haha',e:'my mother'},{j:'あに',r:'ani',e:'my older brother'},{j:'あね',r:'ane',e:'my older sister'},{j:'おとうと',r:'otouto',e:'my younger brother'},{j:'いもうと',r:'imouto',e:'my younger sister'},{j:'けっこんしています',r:'kekkon shiteimasu',e:'is married'},{j:'すんでいます',r:'sunde imasu',e:'lives in'},{j:'はたらいています',r:'hataraite imasu',e:'is working'}]},
  {n:8, title:'バーベキュー', en:'Barbecue',
   grammar:['Short/Plain forms','Short forms in informal speech','〜と思います (I think)','〜と言っていました (said that)','〜ないでください (please don\'t)','Verb のが 好きです','Subject particle が'],
   vocab:[{j:'みじかい',r:'mijikai',e:'short'},{j:'ながい',r:'nagai',e:'long'},{j:'はやい',r:'hayai',e:'fast/early'},{j:'おそい',r:'osoi',e:'slow/late'},{j:'おもい',r:'omoi',e:'heavy'},{j:'かるい',r:'karui',e:'light'},{j:'むずかしい',r:'muzukashii',e:'difficult'},{j:'やさしい',r:'yasashii',e:'easy/kind'},{j:'いそがしい',r:'isogashii',e:'busy'},{j:'ひま(な)',r:'hima(na)',e:'free (time)'}]},
  {n:9, title:'かぶき', en:'Kabuki',
   grammar:['Past tense short forms','Short forms in quoted speech','〜と思います (past thought)','Qualifying nouns with verbs','もう〜ました and まだ〜ていません'],
   vocab:[{j:'おべんとう',r:'obento',e:'boxed lunch'},{j:'おちゃ',r:'ocha',e:'green tea'},{j:'にほんぶんか',r:'nihon bunka',e:'Japanese culture'},{j:'でんとう',r:'dento',e:'tradition'},{j:'ぶたい',r:'butai',e:'stage'},{j:'やく',r:'yaku',e:'role/part'},{j:'かんきゃく',r:'kankyaku',e:'audience'},{j:'すばらしい',r:'subarashii',e:'wonderful'},{j:'たくさん',r:'takusan',e:'many/a lot'},{j:'ひとり',r:'hitori',e:'alone'}]},
  {n:10, title:'ふゆやすみの よてい', en:'Winter Vacation Plans',
   grammar:['Comparison between two items','Comparison among 3+ items','Adjective/Noun + の','〜つもりだ (intend to)','Adjective + なる','どこかに/どこにも'],
   vocab:[{j:'ほっかいどう',r:'Hokkaido',e:'Hokkaido (place)'},{j:'きゅうしゅう',r:'Kyushu',e:'Kyushu (place)'},{j:'りょこう',r:'ryoko',e:'travel'},{j:'よやく',r:'yoyaku',e:'reservation'},{j:'ホテル',r:'hoteru',e:'hotel'},{j:'ツアー',r:'tsua',e:'tour'},{j:'たのしみ',r:'tanoshimi',e:'something to look forward to'},{j:'さむく なります',r:'samuku narimasu',e:'becomes cold'},{j:'どちら',r:'dochira',e:'which (polite)'},{j:'もっと',r:'motto',e:'more'}]},
  {n:11, title:'きのう なにを しましたか', en:'What Did You Do Yesterday',
   grammar:['〜たい (want to do)','〜たり〜たりします','〜ことがある (have done)','Noun A や Noun B'],
   vocab:[{j:'やすみ',r:'yasumi',e:'holiday/day off'},{j:'プール',r:'puru',e:'swimming pool'},{j:'かいもの',r:'kaimono',e:'shopping'},{j:'でかける',r:'dekakeru',e:'go out'},{j:'〜ながら',r:'-nagara',e:'while doing'},{j:'まず',r:'mazu',e:'first of all'},{j:'それから',r:'sorekara',e:'after that'},{j:'そして',r:'soshite',e:'and then'},{j:'だから',r:'dakara',e:'therefore'},{j:'でも',r:'demo',e:'but'}]},
  {n:12, title:'びょうき', en:'Feeling Ill',
   grammar:['〜んです (explaining/seeking confirmation)','〜すぎる (too much)','〜ほうがいい (had better)','〜ので (because)','〜なければいけません','〜でしょうか'],
   vocab:[{j:'あたま',r:'atama',e:'head'},{j:'は',r:'ha',e:'tooth'},{j:'のど',r:'nodo',e:'throat'},{j:'おなか',r:'onaka',e:'stomach'},{j:'かぜ',r:'kaze',e:'cold (illness)'},{j:'ねつ',r:'netsu',e:'fever'},{j:'いたい',r:'itai',e:'painful'},{j:'くすり',r:'kusuri',e:'medicine'},{j:'びょういん',r:'byoin',e:'hospital'},{j:'いしゃ',r:'isha',e:'doctor'}]},
  {n:13, title:'わたしの すきな もの', en:'My Favourite Things',
   grammar:['Plain form + が します','普通形 (plain form review)','Relative clauses (verb modifying noun)','〜と思う','〜と言う'],
   vocab:[{j:'おんがく',r:'ongaku',e:'music'},{j:'えいが',r:'eiga',e:'movie'},{j:'スポーツ',r:'supotsu',e:'sports'},{j:'アニメ',r:'anime',e:'anime'},{j:'マンガ',r:'manga',e:'manga/comics'},{j:'りょうり',r:'ryori',e:'cooking/cuisine'},{j:'しゅみ',r:'shumi',e:'hobby'},{j:'すき(な)',r:'suki(na)',e:'like'},{j:'きらい(な)',r:'kirai(na)',e:'dislike'},{j:'とくい(な)',r:'tokui(na)',e:'good at'}]},
  {n:14, title:'バレンタインデー', en:"Valentine's Day",
   grammar:['〜てあげます/もらいます/くれます (giving & receiving)','〜ていただけませんか (polite request)','〜といいですね'],
   vocab:[{j:'プレゼント',r:'purezento',e:'present/gift'},{j:'チョコレート',r:'chokoreeto',e:'chocolate'},{j:'バレンタインデー',r:'barentain de',e:'Valentine\'s Day'},{j:'おしえます',r:'oshiemasu',e:'teach'},{j:'もらいます',r:'moraimasu',e:'receive'},{j:'あげます',r:'agemasu',e:'give'},{j:'くれます',r:'kuremasu',e:'give (to me)'},{j:'かします',r:'kashimasu',e:'lend'},{j:'かります',r:'karimasu',e:'borrow'},{j:'おくります',r:'okurimasu',e:'send'}]},
  {n:15, title:'まいにちの せいかつ', en:'Daily Life',
   grammar:['〜ておく (do in advance)','〜てしまう (end up doing)','〜てくる/〜ていく','Changes in state','〜ておいてください'],
   vocab:[{j:'そうじします',r:'soji shimasu',e:'clean/tidy up'},{j:'せんたくします',r:'sentaku shimasu',e:'do laundry'},{j:'りょうりします',r:'ryori shimasu',e:'cook'},{j:'かいもの します',r:'kaimono shimasu',e:'go shopping'},{j:'シャワーを あびます',r:'shawa o abimasu',e:'take a shower'},{j:'は を みがきます',r:'ha o migakimasu',e:'brush teeth'},{j:'てを あらいます',r:'te o araimasu',e:'wash hands'},{j:'かおを あらいます',r:'kao o araimasu',e:'wash face'},{j:'ふくを きます',r:'fuku o kimasu',e:'wear clothes'},{j:'くつを はきます',r:'kutsu o hakimasu',e:'wear shoes'}]},
  {n:16, title:'します vs している', en:'Do vs. Doing',
   grammar:['てform + から (after doing)','〜まえに (before)','〜あいだに (while/during)','〜ばかり (just did / only)'],
   vocab:[{j:'まえに',r:'mae ni',e:'before'},{j:'あとで',r:'ato de',e:'after'},{j:'〜てから',r:'-te kara',e:'after doing'},{j:'あいだ',r:'aida',e:'while/between'},{j:'ばかり',r:'bakari',e:'just did / only'},{j:'すでに',r:'sudeni',e:'already'},{j:'まだ',r:'mada',e:'still / not yet'},{j:'もう',r:'mou',e:'already / anymore'},{j:'やっと',r:'yatto',e:'finally'},{j:'すぐ',r:'sugu',e:'right away'}]},
  {n:17, title:'こうつうきかん', en:'Transportation',
   grammar:['〜で (by means of)','Passive form introduction','〜によって','〜のに (for the purpose of)','〜から〜まで'],
   vocab:[{j:'でんしゃ',r:'densha',e:'train'},{j:'バス',r:'basu',e:'bus'},{j:'タクシー',r:'takushi',e:'taxi'},{j:'ひこうき',r:'hikouki',e:'airplane'},{j:'ふね',r:'fune',e:'ship'},{j:'じてんしゃ',r:'jitensha',e:'bicycle'},{j:'のります',r:'norimasu',e:'ride/board'},{j:'おります',r:'orimasu',e:'get off'},{j:'のりかえます',r:'norikae masu',e:'transfer'},{j:'きっぷ',r:'kippu',e:'ticket'}]},
  {n:18, title:'かんじ', en:'Kanji',
   grammar:['〜なければなりません (must do)','〜なくてもいいです (don\'t have to)','〜はずです (supposed to)','〜ようです (seems like)'],
   vocab:[{j:'かんじ',r:'kanji',e:'kanji character'},{j:'よみかた',r:'yomikata',e:'how to read'},{j:'かきかた',r:'kakikata',e:'how to write'},{j:'いみ',r:'imi',e:'meaning'},{j:'おぼえます',r:'oboemasu',e:'memorize'},{j:'わすれます',r:'wasuremasu',e:'forget'},{j:'れんしゅうします',r:'renshu shimasu',e:'practice'},{j:'べんきょうします',r:'benkyo shimasu',e:'study'},{j:'しけん',r:'shiken',e:'exam/test'},{j:'ごうかく',r:'gokaku',e:'pass (exam)'}]},
  {n:19, title:'もしもし', en:'Hello (Phone)',
   grammar:['〜ば (conditional if)','〜たら (conditional when/if)','〜なら (conditional assuming)','Giving/Receiving verbs review'],
   vocab:[{j:'もしもし',r:'moshi moshi',e:'hello (phone)'},{j:'でんわします',r:'denwa shimasu',e:'call (phone)'},{j:'メッセージ',r:'messaji',e:'message'},{j:'メール',r:'meru',e:'email'},{j:'れんらくします',r:'renraku shimasu',e:'contact/notify'},{j:'よていします',r:'yotei shimasu',e:'schedule/plan'},{j:'やくそく',r:'yakusoku',e:'promise/appointment'},{j:'ごろ',r:'goro',e:'around (time)'},{j:'ちょうど',r:'chodo',e:'exactly'},{j:'〜ごろ',r:'-goro',e:'around (time approx)'}]},
  {n:20, title:'わたしは げんき', en:"I'm Fine",
   grammar:['〜そうです (hearsay — I heard)','〜そうです (appearance — looks like)','〜らしいです (apparently/seems)','〜ようです (seems like — inference)'],
   vocab:[{j:'らしい',r:'rashii',e:'apparently / seems'},{j:'そうだ',r:'so da',e:'looks like / I heard'},{j:'ようだ',r:'yo da',e:'seems like (inference)'},{j:'みたいだ',r:'mitai da',e:'looks like (casual)'},{j:'きっと',r:'kitto',e:'surely/definitely'},{j:'たぶん',r:'tabun',e:'probably'},{j:'もしかしたら',r:'moshika shitara',e:'perhaps'},{j:'かならず',r:'kanarazu',e:'certainly/without fail'},{j:'ぜったいに',r:'zettai ni',e:'absolutely'},{j:'はっきり',r:'hakkiri',e:'clearly'}]},
  {n:21, title:'わたしの まち', en:'My Town',
   grammar:['〜ために (for the purpose of)','〜ように (so that)','〜ようにします (try to / make effort)','〜ようになります (come to do)'],
   vocab:[{j:'まち',r:'machi',e:'town/city'},{j:'こうえん',r:'koen',e:'park'},{j:'びじゅつかん',r:'bijutsukan',e:'art museum'},{j:'としょかん',r:'toshokan',e:'library'},{j:'スーパー',r:'supa',e:'supermarket'},{j:'デパート',r:'depato',e:'department store'},{j:'びょういん',r:'byoin',e:'hospital'},{j:'ゆうびんきょく',r:'yubinkyoku',e:'post office'},{j:'こうばん',r:'koban',e:'police box'},{j:'えき',r:'eki',e:'station'}]},
  {n:22, title:'できること', en:'Things I Can Do',
   grammar:['Potential form (can do)','〜ことができます','〜やすい / 〜にくい','〜やすそう / 〜にくそう'],
   vocab:[{j:'できます',r:'dekimasu',e:'can do / is possible'},{j:'およげます',r:'oyogemasu',e:'can swim'},{j:'はなせます',r:'hanasemasu',e:'can speak'},{j:'うんてんできます',r:'unten dekimasu',e:'can drive'},{j:'りょうりできます',r:'ryori dekimasu',e:'can cook'},{j:'やさしい',r:'yasashii',e:'easy (to do)'},{j:'むずかしい',r:'muzukashii',e:'difficult'},{j:'べんり(な)',r:'benri(na)',e:'convenient'},{j:'ふべん(な)',r:'fuben(na)',e:'inconvenient'},{j:'じょうず(な)',r:'jozu(na)',e:'skillful'}]},
  {n:23, title:'にほんの おみやげ', en:'Japanese Souvenirs',
   grammar:['〜たことがあります (have done before)','〜たことがありません (have never done)','〜前に vs 〜後で','Expressing experiences'],
   vocab:[{j:'おみやげ',r:'omiyage',e:'souvenir'},{j:'にんぎょう',r:'ningyo',e:'doll'},{j:'きもの',r:'kimono',e:'kimono'},{j:'おちゃ',r:'ocha',e:'Japanese tea'},{j:'わがし',r:'wagashi',e:'Japanese sweets'},{j:'こうげいひん',r:'kogeihin',e:'craft goods'},{j:'つたわる',r:'tsutawaru',e:'be transmitted/passed on'},{j:'ぶんか',r:'bunka',e:'culture'},{j:'でんとう(な)',r:'dento(na)',e:'traditional'},{j:'ゆうめい(な)',r:'yumei(na)',e:'famous'}]},
  {n:24, title:'おまつり', en:'Festival',
   grammar:['〜たり〜たりします (do things like)','〜ながら (while doing)','Expressing reason/result with から/ので','〜し〜し (listing reasons)'],
   vocab:[{j:'まつり',r:'matsuri',e:'festival'},{j:'はなび',r:'hanabi',e:'fireworks'},{j:'おどります',r:'odorimasu',e:'dance'},{j:'うたいます',r:'utaimasu',e:'sing'},{j:'たいこ',r:'taiko',e:'drum'},{j:'ゆかた',r:'yukata',e:'summer kimono'},{j:'こうえん',r:'koen',e:'park'},{j:'かいじょう',r:'kaijo',e:'venue'},{j:'にぎやか(な)',r:'nigiyaka(na)',e:'lively/bustling'},{j:'たのしい',r:'tanoshii',e:'fun/enjoyable'}]},
  {n:25, title:'スポーツ センター', en:'Sports Centre',
   grammar:['Passive voice (〜られます)','〜てもらいます','〜てくれてありがとう','Expressing gratitude and obligation'],
   vocab:[{j:'スポーツセンター',r:'supotsu senta',e:'sports centre'},{j:'およぎます',r:'oyogimasu',e:'swim'},{j:'はしります',r:'hashirimasu',e:'run'},{j:'トレーニング',r:'toreningu',e:'training'},{j:'うんどうします',r:'undon shimasu',e:'exercise'},{j:'たいりょく',r:'tairyoku',e:'physical strength'},{j:'けんこう',r:'kenkou',e:'health'},{j:'かいいん',r:'kaiin',e:'member'},{j:'かいひ',r:'kaihi',e:'membership fee'},{j:'よやくします',r:'yoyaku shimasu',e:'make a reservation'}]}
];
